[package]
name = "eigenlayer-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.6.4", features = ["full"] }
eyre = "0.6.12"
tokio = { version ="1.41.1", features = ["full"] }
